name: ci-build
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
env:
  CARGO_TERM_COLOR: always
jobs:
  release-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Clone source
        run: |
          git clone --depth 1 https://github.com/ferrocene/ferrocene
      - name: Setup rust toolchains
        run: |
          rustup default nightly
          rustup target add aarch64-linux-android armv7-linux-androideabi x86_64-linux-android i686-linux-android
          rustup component add rust-src
          rustup update
      - name: Other deps
        run: |
          sudo apt update
          sudo apt install gcc-multilib llvm clang make cmake libclang-dev llvm-dev ninja-build
      - name: Build
        run: |
          cd ferrocene
          # sh  ../patch_llvm.sh
          ./configure --enable-cargo-native-static --enable-llvm-static-stdcpp
          sudo chmod +x x.py          
          ./x.py dist --stage 2 || true
          
      - name: Upload release version
        uses: actions/upload-artifact@v4
        with:
          name: config_toml
          compression-level: 9
          path: ferrocene/config.toml
          
          