name: ci-build
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
env:
  CARGO_TERM_COLOR: always
jobs:
  release-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Clone source
        run: |
          git clone --depth 1 https://github.com/ferrocene/ferrocene
      - name: Setup rust toolchains
        run: |
          rustup default nightly
          rustup target add aarch64-linux-android armv7-linux-androideabi x86_64-linux-android i686-linux-android aarch64-unknown-linux-gnu aarch64-unknown-linux-musl
          rustup component add rust-src
          rustup update
      - name: Other deps
        run: |
          sudo apt-get update
          # sudo apt-get upgrade -y
          sudo apt-get install gcc-multilib llvm clang make cmake libclang-dev llvm-dev ninja-build gcc
      - name: Build
        run: |
          cd ferrocene
          cargo build -Z build-std || true
          sh  ../patch_llvm.sh
          sudo chmod +x x.py          
          ./x.py build --stage 2
          
      - name: Upload release version
        uses: actions/upload-artifact@v4
        with:
          name: config_toml
          compression-level: 9
          path: ferrocene/build
          
          